from typing import Optional
import re

# Дилерские марки компании "АвтоЛидер"
DEALER_BRANDS = {"Chery", "Jetour", "Haval"}

BRANDS = {
    "Acura": ["acura", "акура"],
    "Alfa Romeo": ["alfa romeo", "альфаромео", "альфа"],
    "Alpina": ["alpina", "альпина"],
    "Asia": ["asia", "азия"],
    "Aston Martin": ["aston martin", "астон мартин"],
    "Audi": ["audi", "ауди", "аудио"],
    "Bentley": ["bentley", "бентли", "бентлей"],
    "BMW": ["bmw", "бээмвэ", "бмв", "бэха", "беха"],
    "Brilliance": ["brilliance", "брилианс"],
    "Bugatti": ["bugatti", "бугатти", "бугати"],
    "Buick": ["buick", "бьюик", "буик"],
    "BYD": ["byd", "бид", "биайди"],
    "Cadillac": ["cadillac", "каддилак"],
    "Changan": ["changan", "чанган", "чаньян"],
    "Chery": ["chery", "чери"],
    "Chevrolet": ["chevrolet", "шеви", "шевроле", "шевролет"],
    "Chrysler": ["chrysler", "крайслер"],
    "Citroen": ["citroen", "ситроен"],
    "Dacia": ["dacia", "дача", "дачиа"],
    "Daewoo": ["daewoo", "дэу", "деу", "даеву"],
    "Daihatsu": ["daihatsu", "дайхатсу", "дайхацу"],
    "Datsun": ["datsun", "датсун", "дацун"],
    "DeLorean": ["delorean", "делорин"],
    "Derways": ["derways", "дервейс"],
    "Dodge": ["dodge", "додж"],
    "Dongfeng": ["dongfeng", "донфен", "донфенг", "дунфен"],
    "FAW": ["faw", "фав"],
    "Ferrari": ["ferrari", "феррари", "ферари"],
    "Fiat": ["fiat", "фиат"],
    "Ford": ["ford", "форд"],
    "Foton": ["foton", "фотон"],
    "Geely": ["geely", "джили"],
    "Genesis": ["genesis", "генезис", "дженезис"],
    "GMC": ["gmc", "джиэмси", "гмк"],
    "Great Wall": ["great wall", "greet wol", "грет вол", "грейт волл"],
    "Haima": ["haima", "хайма"],
    "Haval": ["haval", "хавал", "хавейл", "хавэйл"],
    "Hino": ["hino", "хино"],
    "Honda": ["honda", "хонда"],
    "Hummer": ["hummer", "хаммер", "хамер"],
    "Hyundai": ["hyundai", "хендэ", "хендай"],
    "Infiniti": ["infiniti", "инфинити"],
    "Iran Khodro": ["iran khodro", "иран кодро"],
    "Isuzu": ["isuzu", "исудзу"],
    "JAC": ["jac", "джак", "жак"],
    "Jaguar": ["jaguar", "ягуар"],
    "Jeep": ["jeep", "джип"],
    "Kia": ["kia", "киа", "кия"],
    "Lamborghini": ["lamborghini", "ламбо", "ламборгини", "ламборджини"],
    "Lancia": ["lancia", "ланчиа", "лянча"],
    "Land Rover": ["land rover", "лэнд ровер"],
    "Lexus": ["lexus", "лексус"],
    "Lifan": ["lifan", "лифан"],
    "Lincoln": ["lincoln", "линкольн"],
    "Lotus": ["lotus", "лотос", "лотус"],
    "Luxgen": ["luxgen", "люксген", "лаксджин"],
    "Marussia": ["marussia", "маруся"],
    "Maserati": ["maserati", "мазерати"],
    "Maybach": ["maybach", "майбах"],
    "Mazda": ["mazda", "мазда"],
    "McLaren": ["mclaren", "макларен"],
    "Mercedes-Benz": ["mercedes-benz", "mercedes", "мерс", "мерседес", "мерин"],
    "Mercury": ["mercury", "меркури"],
    "MINI": ["mini", "мини"],
    "Mitsubishi": ["mitsubishi", "митсу", "мицу", "митсуба", "мицуба", "митсубиси", "мицубиши"],
    "Nissan": ["nissan", "ниссан"],
    "Oldsmobile": ["oldsmobile", "олсмобил", "олдсмобиль"],
    "Opel": ["opel", "опель"],
    "Pagani": ["pagani", "пагани"],
    "Peugeot": ["peugeot", "пежо"],
    "Plymouth": ["plymouth", "плимут"],
    "Pontiac": ["pontiac", "понтиак"],
    "Porsche": ["porsche", "порше", "порш"],
    "Proton": ["proton", "протон"],
    "Ravon": ["ravon", "равон"],
    "Renault": ["renault", "ренно"],
    "Rolls-Royce": ["rolls-royce", "роллсройс"],
    "Rover": ["rover", "ровер"],
    "Saab": ["saab", "сааб"],
    "Saturn": ["saturn", "сатурн"],
    "Scion": ["scion", "сцион", "цион"],
    "SEAT": ["seat", "сеат"],
    "Skoda": ["skoda", "шкода", "шкоду", "шкоды", "шкоде"],
    "Smart": ["smart", "смарт"],
    "SsangYong": ["ssangyong", "санёнг", "ссанёнг"],
    "Subaru": ["subaru", "субару"],
    "Suzuki": ["suzuki", "сузуки", "судзуки"],
    "Tesla": ["tesla", "тесла"],
    "Toyota": ["toyota", "тойота", "тоёта"],
    "Volkswagen": ["volkswagen", "vw", "фв", "фолькс", "фольксваген"],
    "Volvo": ["volvo", "вольво"],
    "Vortex": ["vortex", "вортекс"],
    "Zotye": ["zotye", "зотие"],
    "Aurus": ["aurus", "аурус"],
    "ГАЗ": ["газ", "волга"],
    "ЗАЗ": ["заз"],
    "ИЖ": ["иж"],
    "ВАЗ": ["ваз", "лада", "жигули"],
    "ЛуАЗ": ["луаз"],
    "Москвич": ["москвич"],
    "ТагАЗ": ["тагаз"],
    "УАЗ": ["уаз"],
    "GAC": ["gac", "гак"],
    "Jaecoo": ["jaecoo", "джеку", "джаеку"],
    "Omoda": ["omoda", "омода"],
    "Jetour": ["jetour", "джетур", "жетур"],
    "Tank": ["tank", "танк", "тэнк"],
    "Exeed": ["exeed", "эксид"],
    "Avatr": ["avatr", "аватр"],
    "Baic": ["baic", "байк", "баик"],
    "Bestune": ["bestune", "бэстюн"],
    "Forthing": ["forthing", "фортин", "фортинг", "форфинг"],
    "Hongqi": ["hongqi", "хунчи", "хунцзы", "хунзы"],
    "Kaiyi": ["kaiyi", "кайи", "каи", "кая", "кайя"],
    "Knewstar": ["knewstar", "ньюстар", "кньюстар", "кнюстар"],
    "Li": ["li", "лейсян"],
    "M-Hero": ["m-hero", "эмхиро"],
    "Ora": ["ora", "ора"],
    "Othing": ["othing", "отинг"],
    "Rox": ["rox", "рокс"],
    "Skywell": ["skywell", "скайвел", "скивел"],
    "Soueast": ["soueast", "соист", "соуист"],
    "VGV": ["vgv", "вэгэвэ"],
    "Voyah": ["voyah", "войя", "воя", "вояж"],
    "Wey": ["wey", "вэй", "вей"],
    "Xcite": ["xcite", "икссайт", "иксай", "иксайт"],
    "Tenet": ["tenet", "тенет"],
    "Aito": ["aito", "аито"],
    "Belgee": ["belgee", "белджи", "беджи"],
    "Denza": ["denza", "дэнза"],
    "Evolute": ["evolute", "эволют"],
    "Jetta": ["jetta", "джетта"],
    "Landwind": ["landwind", "ландвин"],
    "Livan": ["livan", "ливан"],
    "Link&Co": ["link&co", "link", "линк и ко", "линк"],
    "MG": ["mg", "эмджи", "эмжи"],
    "Moskvitch": ["moskvitch", "москвич"],
    "Nio": ["nio", "нио"],
    "Polar Stone": ["polar stone", "полар стоун", "поляр стоун"],
    "Roewe": ["roewe", "рёвэ"],
    "Seres": ["seres", "серес", "сирес", "сирис"],
    "SWM": ["swm", "эсвээм"],
    "Wuling": ["wuling", "вулинг", "вулинь"],
    "XPeng": ["xpeng", "икспенг", "кспенг"],
    "Zeekr": ["zeekr", "зикр", "зикер"],
}


class BrandMatcher:
    def __init__(self):
        self.map = BRANDS

    def find_brand(self, text: str) -> Optional[str]:
        """
        Find brand in text using case-insensitive search with word boundaries.
        Returns normalized brand name or None.
        """
        text_lower = text.lower()
        
        # Check each brand and its variants
        for brand, variants in self.map.items():
            for variant in variants:
                # Use word boundaries to avoid partial matches
                pattern = r'\b' + re.escape(variant.lower()) + r'\b'
                if re.search(pattern, text_lower):
                    return brand
        
        return None

